#!/bin/bash

#source $HOME/bin/testSuite/configfile

source ./configfile


declare -a symbols=(3 8 13 25)
declare -a symbolSize=(500 1000 1400)
cd $APSI_DIR
for x in ${symbolSize[*]}; do
	for y in ${symbols[*]}; do
      #edit the file to change the symbols
		perl -pi -e "s/symbols = .*/symbols = ${y}/g" $APSI_TESTDIR/apsi.cfg
      #edit the file to change the symbolSize
		perl -pi -e "s/symbolSize = .*/symbolSize = ${x}/g" $APSI_TESTDIR/apsi.cfg
      #for these changes to take effect the code has to be recompiled
		echo "symbols: ${y} symbolSize: ${x}"
		echo "Press [ENTER] to continue..."
		read -p "$*"
		#mv serverlog serverlog_s${y}_ss${x}.log
		#rExec
	done	
done
