#!/bin/bash

declare -a loss=(0 1 3 5 10 20 30 50)

for x in ${loss[*]}; do
	sudo tc qdisc del dev enp0s3 root
	sudo tc qdisc add dev enp0s3 root netem delay 40ms loss ${x}
	for i in {1..5}; do curl --socks5-hostname localhost:1080 https://images.unsplash.com/photo-1518791841217-8f162f1e1131?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80 > blah; done
done
