#!/bin/bash

declare -a loss=(0 1 3 5 10 20 30 50)

for x in ${loss[*]}; do
	sudo tc qdisc del dev eth0 root
	sudo tc qdisc add dev eth0 root netem delay 40ms loss ${x}
	for i in {1..5}; do curl --socks5-hostname localhost:1080 10.1.1.66/testsuite/random.img > blah; done
done
