#!/bin/bash

#Array declaration with hosts.
SERVER=(workMachine)
TARGET=(192.168.0.5)
#----------------------------------
CLIENT=(localhost)
SOURCE=(workMachine)

#KIMMACHINE

if [ "${KIMMACHINE:=}" ]; then
  #Array declaration with hosts.
  SERVER=(workMachine)
  TARGET=(workMachine)
  #----------------------------------
  CLIENT=(workMachine)
  SOURCE=(workMachine)
else
  #Array declaration with hosts.
  SERVER=(lester-VirtualBox)
  TARGET=("192.168.254.103") #,lester-VirtualBox)
  #----------------------------------
  CLIENT=(localhost) #, lester-VirtualBox)
  SOURCE=(lester-VirtualBox)
fi

PLATFORM="amd64-linux-sysv-dbg"
EC2_PUBLIC="localhost"
EC2_LOCAL="localhost"
MD5SUM="targetMD5Sum"
# the next 3 variables are used in startClient
# I think they are self explanatory
WEBSERVER="192.168.0.5:80"
LOCATION="person/sprinkler"
FILENAME="random1GB"
FILENAMEDEST="random1GB"
#directory for apsi
APSI_DIR="$HOME/APSI/"
#directory or the apsi test directory if you do a clone
# of the test repository it is apsiTests
APSI_TESTDIR="$HOME/apsiTests/"
USER="lester@"
#Home for bin files. Is this necessary? Do I want a / at the end and then change all others to not take a /? #FIXME
BIN_DIR="$HOME"
TEST_DIR="$BIN_DIR/apsiTests"
#This will be for the config file to be used with -f. How to handle separate files?
SERVER_CONFIG=$TEST_DIR/server.cfg
CLIENT_CONFIG=$TEST_DIR/client.cfg
#May want a config file for Traffic Control
#TC="$BIN_DIR/rtc"
COUNT=0

