#!/bin/bash

source ./configfile

echo "ssh "$USER${TARGET[1]}

if [ ! -f $BIN_DIR/$FILENAME ];
then
	ssh $USER${TARGET[1]} $TEST_DIR/ddFile
	ssh $USER${TARGET[1]} $TEST_DIR/getMD5Sum
elif [ ! -f $BIN_DIR/$MD5SUM ];
then
	ssh $USER${TARGET[1]} $TEST_DIR/getMD5Sum
else
	echo -ne "*** File and MD5Sum are current ***\n"
fi
