#!/bin/bash 

source ./configfile

#LinuxMint, Ubuntu, anything that uses service
if pgrep -x "apache2" >/dev/null 2>&1
then 
	echo "Stop apache...."
	./stopApache
fi
if [ $(pidof /sbin/init) -eq 1 ]; then
	echo "calling directly apache2ctl command"
	sudo apache2ctl -f apache2.conf
else 
	echo "calling apache2ctl in /usr/sbin"
	sudo /usr/sbin/apache2ctl -f ./apache2.conf
fi
