#!/bin/bash 
#
#source $HOME/bin/testSuite/configfile
#source $HOME/apsiTests/configfile
source $HOME/workspace/apsiTests/configfile

runClient()
{
	echo "Running client...."
	cd $APSI_DIR
        echo "apsiproxy -c -i $EC2_PUBLIC -f $CLIENT_CONFIG -l client.csv"

	build/$PLATFORM/apsiproxy/apsiproxy -c -i $EC2_PUBLIC -f $CLIENT_CONFIG -l client.csv
echo "return value = $?"
	if [ "$?" -gt "0" ]; then
		exit 1
	fi
	mv client.log client.$(( 1 + $(ls | cut -d . -f 2 | sort -nr | head -1))).$(date +"%Y-%m-%d").log
}

echo "runClient: Current location: $PWD"
runClient
