#!/bin/bash 
#
#source $HOME/bin/testSuite/configfile
source $HOME/apsiTests/configfile

runClient()
{
	echo "Running client...."
	cd $APSI_DIR
	build/$PLATFORM/apsiproxy/apsiproxy -c -i $EC2_PUBLIC -f $CLIENT_CONFIG -l client.csv
	mv client.log client.$(( 1 + $(ls | cut -d . -f 2 | sort -nr | head -1))).$(date +"%Y-%m-%d").log
}

runClient
