#!/bin/bash
#
#source $HOME/bin/testSuite/configfile
source ./configfile

runServer()
{
		cd $APSI_DIR
		build/$PLATFORM/apsiproxy/apsiproxy -s -f $SERVER_CONFIG -l server.csv
echo "return value = $?"
	if [ "$?" -gt "0" ]; then
		exit 1
	fi
		mv server.log server.$(( 1 + $(ls | cut -d . -f 2 | sort -nr | head -1))).$(date +"%Y-%m-%d").log
}

runServer
