#!/bin/bash 
#
#source $HOME/bin/testSuite/configfile
source $HOME/workspace/apsiTests/configfile

runSample() {
    for trial in {1..1};
    do
        ssh $USER${SERVER[0]} workspace/apsiTests/./runServer &
	echo "Sleep for 10 seconds to allow server to run properly"
	sleep 10
        ./runClient &
        sleep .5
        ./runCurl 
        
        wait $!
	scp $USER${SERVER[0]}:$APSI_TESTDIR$MD5SUM $APSI_TESTDIR$MD5SUM #Download targetMD5Sum in the server...
        md5check=`md5sum /tmp/ramdisk/blah | awk '{print $1}'`
        echo $md5check > $TEST_DIR/sourceMD5Sum
        cmp sourceMD5Sum $APSI_TESTDIR$MD5SUM
        echo "Done with run:" $trial

    done
}

echo "Running sampleTest script...."
runSample
