#!/bin/bash 
#
#source $HOME/bin/testSuite/configfile
source $HOME/workspace/apsiTests/configfile

runSample() {
    for trial in {1..1};
    do
        ssh $USER${SERVER[0]} workspace/apsiTests/./runServer &
	echo "Sleep for 10 seconds to allow server to run properly"
	sleep 10
        ./runClient &
        sleep .5
        ./runCurl 
        
        wait $!
        md5check=`md5sum /tmp/ramdisk/blah | awk '{print $1}'`
        echo $md5check > $TEST_DIR/sourceMD5Sum
        cmp sourceMD5Sum targetMD5Sum
        echo "Done with run:" $trial

    done
}

echo "Running sampleTest script...."
runSample
