#!/bin/bash

source $HOME/apsiTests/configfile

#HOST
sendLogs()
{
	#Will probably want to create $MASTER_USER $MASTER_HOST?
	ssh alec@workMachine mkdir -p $BIN_DIR/Logs/$HOST
	rsync -v -e ssh $USER$1:$APSI_DIR/\*logging $BIN_DIR/Logs/$HOST/$COUNT/
	rsync -v -e ssh $USER$1:$APSI_DIR/\*.csv $BIN_DIR/Logs/$HOST/$COUNT/
	rsync -v -e ssh $USER$1:$BIN_DIR/$MD5SUM $BIN_DIR/
	
}

#I need to set HOST as an environmental variable and not a shell variable.. how?
for trial in {1..1};
do
	#echo "runServer..."
	rExec ${SERVER[0]} runServer >/dev/null 2>&1 & 
	#echo "runClient..."
	#rExec ${CLIENT[0]} runClient &
	./runClient >/dev/null 2>&1 & 
	sleep .5
	#echo "runCurl..."
	#rExec ${SOURCE[0]} runCurl #>/dev/null 2>&1
	./runCurl &

	#HOW TO GET THIS SHIT OUT OF "RUN SCRIPT"?
	wait $!
	echo "Download $MD5SUM in $USER${SERVER[0]}:workspace/apsiTests/$MD5SUM and put it in $APSI_TESTDIR$MD5SUM"
	scp $USER${SERVER[0]}:workspace/apsiTests/$MD5SUM $APSI_TESTDIR$MD5SUM #Download targetMD5Sum in the server...
	echo "Check the content of $APSI_TESTDIR"
	ls $APSI_TESTDIR

	sendLogs ${SERVER[0]} >/dev/null 2>&1
	sendLogs ${CLIENT[0]} >/dev/null 2>&1
	md5check=`md5sum /tmp/ramdisk/blah | awk '{print $1}'`
	echo $md5check > $BIN_DIR/blahcmp
	cmp $BIN_DIR/blahcmp $APSI_TESTDIR$MD5SUM
	echo "Done with run:" $trial
	cleanup
	#wait
	COUNT=$((COUNT+1))
done
#ssh $USER${TARGET[0]} workspace/apsiTests/./stopApache
