#!/bin/bash

#adds the module ifb from the kernel.
sudo modprobe ifb
#starts the ifb0 interface and brings it up
sudo ip link set dev ifb0 up               
#adds an ingress qdisc to eth0                                     
sudo tc qdisc add dev eth0 ingress                                    
#This "should" add filter to eth0 qdisc and match tcp traffic then redirect that traffic to ifb0
#sudo tc filter add dev eth0 parent ffff: protocol ip u32 match ip dport 80 0xff flowid :1 action mirred egress redirect dev ifb0 
sudo tc filter add dev eth0 parent ffff: protocol ip u32 match ip protocol 17 0xff flowid :1 action mirred egress redirect dev ifb0
#add qdisc ifb0; also adds root netem delay for that interface.
sudo tc qdisc add dev ifb0 root netem limit 10000 delay $1ms loss $2%



#sudo tc qdisc del dev eth0 root
# sudo tc qdisc add dev eth0 root handle 1: prio
# sudo tc qdisc add dev eth0 parent 1:3 handle 30: netem limit 10000 delay $1ms loss $2%
# #sudo tc filter add dev eth0 parent 1: protocol ip prio 1 u32 match ip dport 80 0xff flowid 1:3
# #sudo tc filter add dev eth0 parent 1: protocol ip prio 1 u32 match ip sport 80 0xff flowid 1:3
# sudo tc filter add dev eth0 parent 1: protocol ip prio 1 u32 match ip protocol 17 0xff flowid 1:3 
# sudo tc qdisc show
