#!/bin/bash

source $HOME/apsiTests/configfile

echo "runServer..."
rExec ${SERVER[0]} runServer >/dev/null 2>&1 & 
echo "runClient..."
rExec ${CLIENT[0]} runClient &
./runClient >/dev/null 2>&1 & 
sleep .5

for i in {1..10}; do
	echo "Hostname:"
	echo $1
	for j in {1..10}; do 
		#curl --socks5-hostname $1:1080 http://xmission.com -w "TTFB: %{time_starttransfer} \n" -H 'Cache-Control: max-age=0, must-revalidate' -o xmission${i}_${j}.html > curl${i}_${j}
		curl --socks5-hostname $1:1080 http://www.google.com -w "TTFB: %{time_starttransfer} \n" -H 'Cache-Control: max-age=0, must-revalidate' -o google${i}_${j}.html > curl${i}_${j}
	done
	#sleep 60
done
