#!/bin/bash

SESSION="BYOBUTEST"
# -2: forces 256 colors
byobu-tmux -2 new-session -d -s $SESSION

#window 0
#byobu-tmux -2 new-session -d -s $SESSION
byobu-tmux rename-window -t $SESSION:0 'InitialWindow'

for i in {1..2};
do 
#byobu new-window
byobu-tmux new-window -t $SESSION:$i -n "Client${i}"

byobu-tmux send-keys "echo 'hello from client ${i}'"

done


echo "At testbyobu: Listing session..."
tmux ls
echo "At testbyobu: Done listing."
echo "At testbyobu: Killing session run..."
tmux kill-session -t $SESSION
echo "At testbyobu: Test if killed:"
tmux ls
echo "At testbyobu: Done killing.."

