#!/bin/bash 
#
#

source $HOME/apsiTests/configfile

cleanup()
{
	echo "ssh $USER${SERVER[0]} $HOME/apsiTests/./runKillAll"
	echo "ssh $USER${CLIENT[0]} $HOME/apsiTests/./runKillAll"
	ssh $USER${SERVER[0]} $HOME/apsiTests/./runKillAll >/dev/null 2>&1 &
	ssh $USER${CLIENT[0]} $HOME/apsiTests/./runKillAll >/dev/null 2>&1 &
	return $?
}

cleanup
